// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhfuhprleqdkcbyftyoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloZnVocHJsZXFka2NieWZ0eW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTc1NjgsImV4cCI6MjA2ODIzMzU2OH0.4uAckQSoYQSvpslOa4WJnCOlYiBYSrk49IlNHbu2vgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});